[package]
name = "fkit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["cargo"]}
#regex = "1.6"
aho-corasick = "0.7"
colored = "2.0.0"
thiserror = "1"